package com.nuoyun.pro.model;

import com.tmsps.ne4spring.annotation.NotMap;
import com.tmsps.ne4spring.annotation.PK;
import com.tmsps.ne4spring.annotation.Table;
import com.tmsps.ne4spring.orm.model.DataModel;

/**
 * Generated by Ne4Spring 
*/

@Table(TableName="ny_user")
public class ny_user extends DataModel {

	@NotMap
	private static final long serialVersionUID = 1L;
	@PK
	private java.lang.String uId;
	private java.lang.String userName;
	private java.lang.String password;
	private java.lang.Integer age;
	private java.util.Date created;
	private java.lang.Integer status;
	public void setUId(java.lang.String uId) {
 		this.uId = uId;
	}

	public void setUserName(java.lang.String userName) {
 		this.userName = userName;
	}

	public void setPassword(java.lang.String password) {
 		this.password = password;
	}

	public void setAge(java.lang.Integer age) {
 		this.age = age;
	}

	public void setCreated(java.util.Date created) {
 		this.created = created;
	}

	public void setStatus(java.lang.Integer status) {
 		this.status = status;
	}

	public java.lang.String getUId() {
		return uId;
	}

	public java.lang.String getUserName() {
		return userName;
	}

	public java.lang.String getPassword() {
		return password;
	}

	public java.lang.Integer getAge() {
		return age;
	}

	public java.util.Date getCreated() {
		return created;
	}

	public java.lang.Integer getStatus() {
		return status;
	}

}